services:
  backend:
    build: .
    container_name: bid-backend
    ports:
      - "8000:8000"
    restart: always
    environment:
      # ğŸ‘‡ ç¢ºä¿æ˜¯ AWS RDS çš„ç¶²å€
      - DATABASE_URL=postgresql://postgres:0830allan@database-1.c8bwi0kmyu9k.us-east-1.rds.amazonaws.com:5432/postgres
      
      # ğŸ‘‡ ç¢ºä¿æ˜¯ AWS Valkey çš„ç¶²å€ (Serverless è¦ç”¨ rediss://)
      - REDIS_URL=rediss://bid-redis-mq2mra.serverless.use1.cache.amazonaws.com:6379
     